# Generated by Django 5.2.17 on 2026-09-23 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('ambito', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delegación',
                'verbose_name_plural': 'Delegaciones',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('dias_computables', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('version_parametros', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Período de Medición',
                'verbose_name_plural': 'Períodos de Medición',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='ItemMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('cuantitativo', 'Cuantitativo'), ('porcentual', 'Porcentual')], default='cuantitativo', max_length=15)),
                ('unidad', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_demo_app.cargo')),
            ],
            options={
                'verbose_name': 'Ítem de Medición',
                'verbose_name_plural': 'Ítems de Medición',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_evidencia', models.CharField(max_length=12, unique=True)),
                ('fecha_actividad', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
                ('accion', models.CharField(max_length=255)),
                ('ingreso_agenda', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validada', 'Validada'), ('rechazada', 'Rechazada'), ('en_correccion', 'En Corrección')], default='pendiente', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_demo_app.itemmedicion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_demo_app.periodo')),
            ],
            options={
                'verbose_name': 'Actividad Registrada',
                'verbose_name_plural': 'Actividades Registradas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_inst', models.CharField(max_length=20, unique=True, verbose_name='Identificador (RUT/ID)')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_demo_app.cargo')),
                ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_demo_app.delegacion')),
                ('roles', models.ManyToManyField(related_name='usuarios', to='admin_demo_app.rol')),
            ],
            options={
                'verbose_name': 'Usuario Funcionario',
                'verbose_name_plural': 'Usuarios Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/%Y/%m/')),
                ('formato', models.CharField(max_length=10)),
                ('tamanio_bytes', models.PositiveIntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_correccion', 'En Corrección')], default='pendiente', max_length=15)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='admin_demo_app.actividad')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_demo_app.usuario')),
            ],
            options={
                'verbose_name': 'Evidencia Adjunta',
                'verbose_name_plural': 'Evidencias Adjuntas',
            },
        ),
        migrations.AddField(
            model_name='delegacion',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegaciones_a_cargo', to='admin_demo_app.usuario'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_demo_app.usuario'),
        ),
    ]
