# Generated by Django 5.2.17 on 2026-09-23 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_demo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaUsuaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_anonima', models.CharField(max_length=40, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Persona Usuaria',
                'verbose_name_plural': 'Personas Usuarias',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemmedicion',
            name='formula_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AjusteIncentivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('incentivo', 'Incentivo'), ('penalizacion', 'Penalización')], max_length=12)),
                ('motivo', models.CharField(max_length=255)),
                ('valor_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ajustes_recibidos', to='admin_demo_app.usuario')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_demo_app.periodo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ajustes_autorizados', to='admin_demo_app.usuario')),
            ],
            options={
                'verbose_name': 'Ajuste de Incentivo',
                'verbose_name_plural': 'Ajustes de Incentivos',
            },
        ),
        migrations.CreateModel(
            name='AlertaRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vencimiento_compromiso', 'Vencimiento de compromiso'), ('evidencia_pendiente', 'Evidencia pendiente'), ('avance_bajo_umbral', 'Avance bajo umbral')], max_length=25)),
                ('umbral', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reglas_alerta_creadas', to='admin_demo_app.usuario')),
                ('rol_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_demo_app.rol')),
            ],
            options={
                'verbose_name': 'Regla de Alerta',
                'verbose_name_plural': 'Reglas de Alertas',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_ref', models.CharField(max_length=60)),
                ('id_entidad_ref', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisada', 'Revisada')], default='pendiente', max_length=9)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alertas_recibidas', to='admin_demo_app.usuario')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alertas', to='admin_demo_app.alertaregla')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
        migrations.CreateModel(
            name='CatalogoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('actividad', 'Actividad'), ('servicio', 'Servicio'), ('atencion', 'Atención'), ('subatencion', 'Subatención')], max_length=15)),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('area', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='admin_demo_app.catalogotipo')),
            ],
            options={
                'verbose_name': 'Tipo de Catálogo',
                'verbose_name_plural': 'Tipos de Catálogo',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='catalogo_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='admin_demo_app.catalogotipo'),
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=150)),
                ('territorio', models.CharField(blank=True, max_length=120, null=True)),
                ('area_apoyo', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_comprometida', models.DateField()),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('realizado', 'Realizado')], default='ingresado', max_length=12)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actividad_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_demo_app.actividad')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compromisos', to='admin_demo_app.delegacion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compromisos_responsable', to='admin_demo_app.usuario')),
            ],
            options={
                'verbose_name': 'Compromiso',
                'verbose_name_plural': 'Compromisos',
            },
        ),
        migrations.CreateModel(
            name='CompromisoEstadoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('ingresado', 'Ingresado'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('realizado', 'Realizado')], max_length=12, null=True)),
                ('estado_nuevo', models.CharField(choices=[('ingresado', 'Ingresado'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('realizado', 'Realizado')], max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cambios_compromisos', to='admin_demo_app.usuario')),
                ('compromiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='admin_demo_app.compromiso')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Compromiso',
                'verbose_name_plural': 'Historial de Estados de Compromisos',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad', models.CharField(blank=True, max_length=30, null=True)),
                ('ponderador_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umbral_minimo_pct', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('maximo_computable_pct', models.DecimalField(decimal_places=2, default=150.0, max_digits=5)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='metas_creadas', to='admin_demo_app.usuario')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='admin_demo_app.cargo')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='metas_asignadas', to='admin_demo_app.usuario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_demo_app.itemmedicion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_demo_app.periodo')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avance_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cumplimiento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('meta_esperada_dia_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cumplimiento_ponderado', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('semaforo', models.CharField(choices=[('verde', 'Verde'), ('ambar', 'Ámbar'), ('rojo', 'Rojo')], default='rojo', max_length=5)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='indicadores', to='admin_demo_app.usuario')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='indicadores', to='admin_demo_app.meta')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='AtencionSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_gestion', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField()),
                ('resultado', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_demo_app.actividad')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='atenciones_sociales', to='admin_demo_app.usuario')),
                ('catalogo_tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_demo_app.catalogotipo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='atenciones', to='admin_demo_app.personausuaria')),
            ],
            options={
                'verbose_name': 'Atención Social',
                'verbose_name_plural': 'Atenciones Sociales',
            },
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('correccion', 'En corrección')], max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='admin_demo_app.evidencia')),
                ('verificador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='validaciones_realizadas', to='admin_demo_app.usuario')),
            ],
            options={
                'verbose_name': 'Validación',
                'verbose_name_plural': 'Validaciones',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar'), ('validar', 'Validar'), ('cambiar_estado', 'Cambiar estado'), ('acceso_denegado', 'Acceso denegado')], max_length=16)),
                ('entidad', models.CharField(max_length=60)),
                ('id_entidad', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='admin_demo_app.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'indexes': [models.Index(fields=['entidad', 'id_entidad'], name='admin_demo__entidad_34387c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='meta',
            constraint=models.CheckConstraint(check=models.Q(('valor_objetivo__gt', 0)), name='meta_valor_objetivo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='indicador',
            constraint=models.UniqueConstraint(fields=('funcionario', 'meta'), name='indicador_funcionario_meta_unico'),
        ),
        migrations.AddConstraint(
            model_name='atencionsocial',
            constraint=models.UniqueConstraint(fields=('persona', 'orden_gestion'), name='atencion_persona_orden_unico'),
        ),
        migrations.AddConstraint(
            model_name='atencionsocial',
            constraint=models.CheckConstraint(check=models.Q(('orden_gestion__gte', 1), ('orden_gestion__lte', 3)), name='atencion_orden_valido'),
        ),
    ]
