# Generated by Django 5.2.17 on 2026-09-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_demo_app', '0002_personausuaria_actividad_contacto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='vigencia_desde',
            field=models.DateField(blank=True, null=True),
        ),
    ]
